### PR TITLE
BG-19296 Enable lint test for KRSv2

### PR DESCRIPTION
**Pull request by james8nguyen**
## JIRA Ticket

[https://bitgoinc.atlassian.net/browse/BG-19296](https://bitgoinc.atlassian.net/browse/BG-19296)

## Change Description

@cooncesean, @tylerlevine, and @marktoda, as a follow-up to our past conversations, I have enabled lint test as part of the CI pipeline. Unfortunately, there are errors and warnings from the test based on the current .eslintrc.json. What would you like to do as far as fixing the lint errors / warnings? Do you someone to do so?

## Tests

Please refer to the lint test errors and warnings here.
https://drone.bitgo-dev.com/BitGo/key-recovery-service-v2/26/1/4

### CODE REVIEW

**Comment by james8nguyen** [comment]
> Cool, this is a good step, now just need to get the unit tests working and we should have a green build. Thanks for working on this @james8nguyen and @marktoda

Thank you, @tylerlevine and @marktoda.
Regarding the failing unit tests, who can fix them or should I disable unit tests temporarily?

**Comment by marktoda** [comment]
Hey @tylerlevine mind rereviewing? I decided to finish the job so this doesn't sit and rot any longer

**Comment by marktoda** [comment]
broken tests were mostly just unyielded functions

**Comment by marktoda** [comment]
Replaced by https://github.com/BitGo/key-recovery-service-v2/pull/73

**Pull request closed without merging**
